# Generated by Django 4.0.4 on 2022-05-20 17:15

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=255)),
                ('CategoryIcon', models.ImageField(upload_to='<django.db.models.fields.CharField>_Icon/')),
                ('CategoryColor', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='MagazineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MagazineName', models.CharField(max_length=255)),
                ('CoverImage', models.ImageField(upload_to='<django.db.models.fields.CharField>_Cover/')),
                ('MagazineIssueDate', models.DateField()),
                ('RentPrice', models.IntegerField()),
                ('BuyPrice', models.IntegerField()),
                ('MagazineDescription', models.TextField(max_length=500)),
                ('Rating', models.IntegerField(default=0)),
                ('IsPromoted', models.BooleanField(default=False)),
                ('Background', colorfield.fields.ColorField(default='#ff0000', image_field=None, max_length=18, samples=None)),
                ('MagazineCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MagazineApp.magazinecategory')),
            ],
        ),
        migrations.CreateModel(
            name='MegazinePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageNumber', models.IntegerField()),
                ('Pages', models.FileField(upload_to='PageNumber_<django.db.models.fields.IntegerField>')),
                ('ChooseMagazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MagazineApp.magazinedetails')),
            ],
        ),
    ]
