# Generated by Django 4.0.4 on 2022-05-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagazineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinecategory',
            name='CategoryIcon',
            field=models.ImageField(upload_to='Category_Icon/'),
        ),
        migrations.AlterField(
            model_name='magazinedetails',
            name='CoverImage',
            field=models.ImageField(upload_to='Megazine_Cover/'),
        ),
        migrations.AlterField(
            model_name='megazinepages',
            name='Pages',
            field=models.FileField(upload_to='PageNumber/'),
        ),
    ]
