# Generated by Django 4.0.4 on 2022-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagazineApp', '0002_alter_magazinecategory_categoryicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinecategory',
            name='CategoryIcon',
            field=models.ImageField(blank=True, null=True, upload_to='Category_Icon/'),
        ),
    ]
