# Generated by Django 4.0.4 on 2022-05-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MagazineApp', '0003_alter_magazinecategory_categoryicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinecategory',
            name='CategoryIcon',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Category_Icon/'),
        ),
    ]
